### PR TITLE
Basic travis config with postgres

### PR DESCRIPTION
**Pull request by bryanhuntesl**

### CODE REVIEW

**Comment by sescobb27** [comment]
@bryanhuntesl tests are not passing
> `The command "PGPASSWORD=postgres until psql -h localhost -U "postgres" -P $RELEASE_ADMIN_POSTGRES_PORT -c '\q' &> /dev/null ; do printf '.'; sleep 1; done" failed and exited with 1 during .`

**Comment by sescobb27** [comment]
what about just using the Postgres service from travis ci? if at some point we need to upgrade or need a custom feature or something we can spend more time on this. what do you think?

**Comment by bryanhuntesl** [comment]
Compiling 42 files (.ex)
warning: variable "github_oauth" is unused
  test/support/stubs_generation.ex:5
Generated release_admin app
** (Postgrex.Error) ERROR 42704 (undefined_object): type "jsonb" does not exist

**Comment by bryanhuntesl** [comment]
@sescobb27 - postgres provided by travis does not support jsonb (didn't realise we were using it). 

My code exposes env var RELEASE_ADMIN_POSTGRES_PORT at build time, but our config is hard coded to use localhost on default port : 

https://github.com/sescobb27/release_admin/blob/107fdba2340862a6822d9750e72450f51db93676/config/test.exs#L16-L22

How would you like to proceed? I'm at code mesh today so availability will be patchy.

**Comment by bryanhuntesl** [comment]
When it generates the message : 

```
Compiling 42 files (.ex)
warning: variable "github_oauth" is unused
test/support/stubs_generation.ex:5
Generated release_admin app
** (Postgrex.Error) ERROR 42704 (undefined_object): type "jsonb" does not exist
```

That's release_admin talking to the travis postgres instance on the default port - the docker instance is running but `release_admin` is not talking to it.

Would be nice if the configuration could be communcated to this application via env vars ala [The twelve factor app (config)](https://12factor.net/config).

Does that make sense?

**Comment by bryanhuntesl** [comment]
Hmmm. Maybe we should also consider if we can reduce the number of config files as a secondary objective.

screenshot 2018-11-09 at 13 42 11

**Comment by sescobb27** [comment]
Ok got it, then, can use `ReleaseAdmin.Repo.init` function for getting config from runtime using `System.get_env` or `RuntimeConfig` module with postgres default values as defaults if no ENV was set, thoughts?

**Comment by bryanhuntesl** [comment]
Yes something like that - would be nice if we had a single config module that handled all this stuff in one place rather than having it (reading env vars) spread all over the codebase.

**Comment by bryanhuntesl** [comment]
Just been looking at [confex](https://github.com/Nebo15/confex) with Lazslo H - I wonder if it would make a good solution to config from ENV (with defaults) - might be better than rolling our own. Will ping on hipchat.

**Pull request merged**
